/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CitizenDashboardRouteImport } from './routes/citizen.dashboard'
import { Route as CitizenNotificationsRouteImport } from './routes/citizen.notifications'
import { Route as CitizenProfileRouteImport } from './routes/citizen.profile'
import { Route as CitizenReportRouteImport } from './routes/citizen.report'
import { Route as CitizenComplaintsIdRouteImport } from './routes/citizen.complaints.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenDashboardRoute = CitizenDashboardRouteImport.update({
  id: '/citizen/dashboard',
  path: '/citizen/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenNotificationsRoute = CitizenNotificationsRouteImport.update({
  id: '/citizen/notifications',
  path: '/citizen/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenProfileRoute = CitizenProfileRouteImport.update({
  id: '/citizen/profile',
  path: '/citizen/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenReportRoute = CitizenReportRouteImport.update({
  id: '/citizen/report',
  path: '/citizen/report',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenComplaintsIdRoute = CitizenComplaintsIdRouteImport.update({
  id: '/citizen/complaints/$id',
  path: '/citizen/complaints/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/citizen/dashboard': typeof CitizenDashboardRoute
  '/citizen/notifications': typeof CitizenNotificationsRoute
  '/citizen/profile': typeof CitizenProfileRoute
  '/citizen/report': typeof CitizenReportRoute
  '/citizen/complaints/$id': typeof CitizenComplaintsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/citizen/dashboard': typeof CitizenDashboardRoute
  '/citizen/notifications': typeof CitizenNotificationsRoute
  '/citizen/profile': typeof CitizenProfileRoute
  '/citizen/report': typeof CitizenReportRoute
  '/citizen/complaints/$id': typeof CitizenComplaintsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/citizen/dashboard': typeof CitizenDashboardRoute
  '/citizen/notifications': typeof CitizenNotificationsRoute
  '/citizen/profile': typeof CitizenProfileRoute
  '/citizen/report': typeof CitizenReportRoute
  '/citizen/complaints/$id': typeof CitizenComplaintsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/citizen/dashboard'
    | '/citizen/notifications'
    | '/citizen/profile'
    | '/citizen/report'
    | '/citizen/complaints/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/citizen/dashboard'
    | '/citizen/notifications'
    | '/citizen/profile'
    | '/citizen/report'
    | '/citizen/complaints/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/citizen/dashboard'
    | '/citizen/notifications'
    | '/citizen/profile'
    | '/citizen/report'
    | '/citizen/complaints/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  CitizenDashboardRoute: typeof CitizenDashboardRoute
  CitizenNotificationsRoute: typeof CitizenNotificationsRoute
  CitizenProfileRoute: typeof CitizenProfileRoute
  CitizenReportRoute: typeof CitizenReportRoute
  CitizenComplaintsIdRoute: typeof CitizenComplaintsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/dashboard': {
      id: '/citizen/dashboard'
      path: '/citizen/dashboard'
      fullPath: '/citizen/dashboard'
      preLoaderRoute: typeof CitizenDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/notifications': {
      id: '/citizen/notifications'
      path: '/citizen/notifications'
      fullPath: '/citizen/notifications'
      preLoaderRoute: typeof CitizenNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/profile': {
      id: '/citizen/profile'
      path: '/citizen/profile'
      fullPath: '/citizen/profile'
      preLoaderRoute: typeof CitizenProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/report': {
      id: '/citizen/report'
      path: '/citizen/report'
      fullPath: '/citizen/report'
      preLoaderRoute: typeof CitizenReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/complaints/$id': {
      id: '/citizen/complaints/$id'
      path: '/citizen/complaints/$id'
      fullPath: '/citizen/complaints/$id'
      preLoaderRoute: typeof CitizenComplaintsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  CitizenDashboardRoute: CitizenDashboardRoute,
  CitizenNotificationsRoute: CitizenNotificationsRoute,
  CitizenProfileRoute: CitizenProfileRoute,
  CitizenReportRoute: CitizenReportRoute,
  CitizenComplaintsIdRoute: CitizenComplaintsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
